### ISSUE TITLE
Example Steps to actually run edgevpn using 3 separate servers

### ISSUE THREAD

**Issue by bmullan** [mudler/edgevpn#142]
I installed edgevpn binary on 3 separate Ubuntu 22.04 machines.

On one of the machines I was trying to follow the edgevpn Documentation but am unsure of these command examples:

> *An example of running edgevpn on multiple hosts:*
>
> \# on Node A
> **$ EDGEVPNTOKEN=.. edgevpn --address 172.16.1.1/12**
> \# on Node B
> **$ EDGEVPNTOKEN=.. edgevpn --address 172.16.1.2/12**
> \# on Node C ...
> **$ EDGEVPNTOKEN=.. edgevpn --address 171.16.1.3/12**

I thought I'd just create a simple Bash script called startvpn.sh on each Host that looked something like:

> ***\#!/bin/bash***
> **EDGEVPNTOKEN=$(edgevpn -g -b)***
> ***edgevpn --address 172.16.1.1/12 --token=$EDGEVPNTOKEN***

But my **installvpn.sh** script ***does not*** to work in *starting the VPN*! 

I then saw another Open Issue with the following example commands for starting Edgevpn & I tried them but using slightly modified command and 172.16.x.x IPs ***and these worked !***

*<h4>on Host 1</h4>* 
>
> **$ sudo ./edgevpn --interface edgevpn0 --config config.yaml  --address 172.16.1.1/12 --transient-conn &**
>  
*<h4>on Host 2</h4>*  
>  
> **$ sudo ./edgevpn --interface edgevpn0 --config config.yaml --address 172.16.1.2/12 --transient-conn &**
>
*<h4>on Host 3</h4>*  
>  
> **$ sudo ./edgevpn --interface edgevpn0 --config config.yaml --address 172.16.1.3/12 --transient-conn &** 

thanks
brian

**Comment by etesami** [comment]
You need to use the same config file or the token across all hosts. The binary token or the YAML config file contains information needed by each host to find other peers.
