### ISSUE TITLE
Is it possible to have access levels?

### ISSUE THREAD

**Issue by sardaukar** [mudler/edgevpn#147]
EdgeVPN sounds great on paper for a project of mine in which servers can be added to a network by third-parties - but I wouldn't want those to be able to access the API, I just want to be able to send and receive network requests to/from them.

Is it possible to prevent joiners from having access to the API?

**Comment by mudler** [comment]
the closest concept there is available as access level is the peerguardian - it basically allows only a group of trusted nodes to modify the ledger states. you can read a little bit more about it here: https://mudler.github.io/edgevpn/docs/concepts/overview/peerguardian/

**Comment by sardaukar** [comment]
Thanks for the response, closing
