### ISSUE TITLE
wintun support

### ISSUE THREAD

**Issue by vip123456789** [mudler/edgevpn#17]
I hope edgevpn can support wintun, thanks!
https://www.wintun.net/

**Comment by mudler** [comment]
Thanks for filing an issue about this!

yes, this is something that was in top of my head already but didn't had time to have a dig nto it yet, besides, I don't have a windows machine to test on, so will take a bit of time from my side.

**Comment by dukzcry** [comment]
I don't have windows machine on home too, I use VM for such cases :-)
Back to deal. I've tried this branch few months ago https://github.com/mudler/edgevpn/tree/wintun
It was very flaky

**Comment by mudler** [comment]
thanks @dukzcry ! Seems someone have patched https://github.com/dtlslink/water/commit/daf4264fd3eeb0fbd6bb48aee617320929d5201d so it can be directly used with the same lib. I'm going to give it a shot over the weekend

**Comment by dukzcry** [comment]
@mudler Please let me know when you form the branch. I will test.
Most likely additional patches like these will be needed:
https://github.com/repos-holder/edgevpn/commit/bbdd67f1feda7e4c8e278b2d91804de916766da5
https://github.com/repos-holder/edgevpn/commit/37d22970fb58991044a9eb2a1e2e97d9f361da38

**Comment by mudler** [comment]
@dukzcry just gave a stab at it https://github.com/mudler/edgevpn/tree/pin/water

**Comment by dukzcry** [comment]
@mudler Thank you! It works at first glance. Need to test it with remote peers.
Could you please also pick https://github.com/repos-holder/edgevpn/commit/fd9d64a9b98b120b6e87e91fdc1d4c29c56328f5 ? It works fine without hack that was needed for `fumiama/water` solution

**Comment by mudler** [comment]
@dukzcry pushed on the branch, thanks!

**Comment by dukzcry** [comment]
@mudler I've tested `pin/water` on remote peers during weekend, works fine so far 🤗

**Comment by mudler** [comment]
That's a great news! Thanks @dukzcry for confirming that out!

**Comment by vip123456789** [comment]
wintun can not works well~
![QQ截图20221017112831](https://user-images.githubusercontent.com/25112835/196083402-0d1f03a4-952a-4669-88d3-6829278067e2.png)

**Comment by vip123456789** [comment]
The adapter failed to obtain the correct ip
![QQ截图20221017115441](https://user-images.githubusercontent.com/25112835/196086175-d89ccdcb-406c-4e47-ba6b-273ccd0e010d.png)

**Comment by dukzcry** [comment]
@vip123456789 
Check that wintun adapter IP is not clashing with existing OpenVPN adapter. Change or clear IP for OpenVPN interface

**Comment by vip123456789** [comment]
> @vip123456789 Change or clear IP for OpenVPN interface. Most likely it clashes with one you want set for wintun

Thanks! Problem solved！
