### ISSUE TITLE
Support for *BSD?

### ISSUE THREAD

**Issue by anoduck** [mudler/edgevpn#30]
Just curious if there is any support for OpenBSD, or any other bsd for that matter?

**Comment by mudler** [comment]
Good point!

I didn't checked if the underlaying tubn libs supports it, if it does should be working.
I'll have a look at that, thanks for bring this up!

**Comment by anoduck** [comment]
@mudler I know for sure there is some support for tunnels, after all OpenBSD is famous for it's routing and firewall, but as for the specific library in question, I do not know. I can look it up on my system if you know offhand the names of the library files in question. 

If it is any help whatsoever: [The FAQ Networking page](https://www.openbsd.org/faq/faq6.html "FAQ: Networking")

and a good source for discovering what extra libraries are available is [Open Ports](https://openports.se "Open Ports")

**Comment by mudler** [comment]
Seems someone patched the underlying lib used for tun/tap for openBSD: https://github.com/derrick658/water/commit/7dd4a78ba9451ac28603cdff8ed682d0ba69f311, so this sounds definitely doable.

**Comment by anoduck** [comment]
> Seems someone patched the underlying lib used for tun/tap for openBSD: [derrick658/water@7dd4a78](https://github.com/derrick658/water/commit/7dd4a78ba9451ac28603cdff8ed682d0ba69f311), so this sounds definitely doable.

Sweetness!

**Comment by mudler** [comment]
I'll give it a shot in the weekend, at least we can get something to build against and try out :)

**Comment by mudler** [comment]
@anoduck ok, this builds: https://github.com/mudler/edgevpn/commit/7adff5289db79213b6a2c96a1a29f47083f75015 however the netlink part which sets up the interface is not available for FreeBSD so I have tossed some commands which probably are wrong - but as I'm not a FreeBSD expert I'd appreciate some help if you can play with that part!

**Comment by anoduck** [comment]
@mudler Will do. Awesome, I am so excited! Happy dance time!

**Comment by anoduck** [comment]
@mudler And, so it begins... 

Got these two errors during build:

```go
pkg/vpn/interface.go:27:56: unknown field 'Persist' in struct literal of type water.PlatformSpecificParams
pkg/vpn/interface.go:29:9: config.Name undefined (type water.Config has no field or method Name)
```

Of course, the use of [persist](https://github.com/mudler/edgevpn/blob/master/pkg/vpn/interface.go#L27) leads to the failure of [water.config](https://github.com/mudler/edgevpn/blob/master/pkg/vpn/interface.go#L31). I attempted to swap out `interface.go` with `interface_darwin.go`, but then both [createInterface](https://github.com/mudler/edgevpn/blob/master/pkg/vpn/vpn.go#L65) and [prepareInterface](https://github.com/mudler/edgevpn/blob/master/pkg/vpn/vpn.go#L114) became undefined. 

I am going to have to look more deeply into [water's process of creating a new interface](https://github.com/derrick658/water/commit/7dd4a78ba9451ac28603cdff8ed682d0ba69f311) OpenBSD's means of network interface configuration is more eccentric than FreeBSD's. If I remember correctly, FreeBSD's interface configuration is almost Linux-ish. It has been a while since I installed a fresh FreeBSD system, and after programming for a few hours, my mental faculties are spent. 

Looking on the bright side, at least we are not working on HURD's network stack. It was completely foreign from my experience.

**Comment by anoduck** [comment]
@mudler After making changes to the buffer space, The script started all right, then exited with `unrecognized driver`.

AND OpenBSD... the error above.

**Comment by anoduck** [comment]
@mudler You know I run OpenBSD, not FreeBSD, right?

**Comment by mudler** [comment]
apologize to get back at you late!  I'll try to play with it in the weekend and see. I'm not a *BSD user, so will take a bit from my side, I'll check if at least we can get away from compiler errors

**Comment by anoduck** [comment]
@mudler No worries, from everything I can gather you are a polite and very busy individual. There is no rush, things are crazy in my corner of the pond as well.
